---
name: Mark Fleming Tennis
description: Tennis professional in Milwaukee WI
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
footer-links:
  dribbble: 
  email: mdfleming3@gmail.com
  facebook: 
  flickr: 
  github: ''
  instagram: 
  linkedin: https://www.linkedin.com/in/mark-fleming-ms-uspta-elite-8b118257/
  pinterest: 
  rss: 
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
url: 
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: ":expanded"
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
